# NORMALIZATION PROBLEM

In [4]:
import numpy as np

In [8]:
# Generate a 5x5 array of random numbers between 0 and 1
x = np.random.rand(5, 5)
print("Original ndarray: ")
print(x)

# Calculate the mean and standard deviation of the array
x_mean = x.mean()
x_std = x.std()

print("\nMean of x:", x_mean)
print("Standard deviation of x:", x_std)

# Normalize the ndarray using the formula Z = (X - X_mean) / X_std
x_normalized = (x - x_mean) / x_std

# Save the normalized array
np.save('X_normalized.npy', x_normalized)

print("\nNormalized ndarray:")
print(x_normalized)

Original ndarray: 
[[0.61447076 0.30121163 0.53555784 0.17956076 0.54870561]
 [0.53499199 0.85401645 0.96070826 0.44255425 0.41863642]
 [0.14049729 0.96659399 0.07630745 0.36966559 0.49451961]
 [0.11627984 0.15735641 0.63481669 0.79508783 0.56836751]
 [0.20281784 0.16804421 0.00883026 0.60100604 0.17357142]]

Mean of x: 0.4345670387618228
Standard deviation of x: 0.27387588611339886

Normalized ndarray:
[[ 0.65688045 -0.48691913  0.36874659 -0.93110162  0.41675291]
 [ 0.36668052  1.53153102  1.92109364  0.02916363 -0.05816728]
 [-1.07373363  1.94258413 -1.30810929 -0.23697395  0.21890418]
 [-1.16215853 -1.01217612  0.73116933  1.3163656   0.48854419]
 [-0.84618328 -0.97315185 -1.55448799  0.60771689 -0.95297041]]


# Divisible by 3 Problem

In [5]:
# Create an array of squares from 1 to 100
A = np.arange(1, 101)**2
A = A.reshape(10, 10)
# Select elements from the array that are divisible by 3
div_by_3 = A[A % 3 == 0]
# Save the selected elements to a .npy file for later use
np.save('div_by_3.npy', div_by_3)

def display_div_by_3(A):
    rows, cols = A.shape
    for i in range(rows):
        row_str = ""
        for j in range(cols):
            row_str += f"{A[i, j]:<6} "  # Display the actual element with a width of 6 characters
        print(row_str)

# Print a message indicating the output of the following array
print("Array of Squares divisible by 3: ")
print(div_by_3)

Array of Squares divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
