# NORMALIZATION PROBLEM

In [2]:
import numpy as np

In [3]:
# Generate a 5x5 array of random numbers between 0 and 1
x = np.random.rand(5, 5)
print ("Original ndarray: ")
print(x)

# Normalize the ndarray to a range between 0 and 1
x_normalized = ((x - x.min()) / (x.max() - x.min()))
np.save('x_normalize.npy', x_normalized)
print ("\nNormalize ndarray:")
print(x_normalized)
print(x)

Original ndarray: 
[[0.95284969 0.53640858 0.551173   0.63763289 0.06390933]
 [0.03923288 0.92515881 0.40574277 0.95675961 0.43254081]
 [0.71984725 0.73622563 0.5405697  0.83575838 0.13358158]
 [0.2484958  0.60750606 0.8016029  0.77665325 0.21719091]
 [0.98732653 0.2049922  0.13812807 0.11925317 0.44354444]]

Normalize ndarray:
[[0.96363562 0.52439514 0.53996788 0.63116129 0.02602744]
 [0.         0.93442872 0.38657562 0.9677596  0.4148408 ]
 [0.71787673 0.73515179 0.52878407 0.84013378 0.09951412]
 [0.22071968 0.59938507 0.80410835 0.77779275 0.1877009 ]
 [1.         0.17483433 0.10430952 0.08440125 0.42644687]]
[[0.95284969 0.53640858 0.551173   0.63763289 0.06390933]
 [0.03923288 0.92515881 0.40574277 0.95675961 0.43254081]
 [0.71984725 0.73622563 0.5405697  0.83575838 0.13358158]
 [0.2484958  0.60750606 0.8016029  0.77665325 0.21719091]
 [0.98732653 0.2049922  0.13812807 0.11925317 0.44354444]]


# Divisible by 3 Problem

In [5]:
# Create an array of squares from 1 to 100
A = np.arange(1, 101)**2
A = A.reshape(10, 10)
# Select elements from the array that are divisible by 3
div_by_3 = A[A % 3 == 0]
# Save the selected elements to a .npy file for later use
np.save('div_by_3.npy', div_by_3)

def display_div_by_3(A):
    rows, cols = A.shape
    for i in range(rows):
        row_str = ""
        for j in range(cols):
            row_str += f"{A[i, j]:<6} "  # Display the actual element with a width of 6 characters
        print(row_str)

# Print a message indicating the output of the following array
print("Array of Squares divisible by 3: ")
print(div_by_3)

Array of Squares divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
